apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gigxpad-dev
resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- ingress.yaml

images:
- name: xpad-bko
  newName: 622054843987.dkr.ecr.eu-west-2.amazonaws.com/gigxpad-web
  newTag: 15cf5fda07a7cd941f4657ccd3218a7cd680cd62-bko
