apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: xpad-bko-ingress
    namespace: gigxpad-prod
    annotations:
        kubernetes.io/ingress.class: nginx
        ngress.kubernetes.io/rewrite-target: /$1
        #cert-manager.io/cluster-issuer: "letsencrypt-prod"
        #kubernetes.io/tls-acme: "true"

spec:
<<<<<<< HEAD
    rules:
        - host: bko.gigxpad.com
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: xpad-bko
                            port:
                                number: 3000
=======
  rules:
    - host: bko.gigxpad.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: xpad-bko
                port:
                  number: 3000
>>>>>>> ab3ba90b9afe25107b0e64731f2a68f4c3f98afe
