apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gigxpad-prod
resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- ingress.yaml

images:
- name: xpad-bko
  newName: 622054843987.dkr.ecr.eu-west-2.amazonaws.com/gigxpad-web
  newTag: 47cfadd6050b6dd5102632101d4bca5250e8cd24-bko
