apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gigxpad-prod
resources:
    - deployment.yaml
    - service.yaml
    - configmap.yaml
    - ingress.yaml

images:
    - name: xpad-bko
