apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gigxpad-stagging
resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- ingress.yaml


images:
- name: xpad-bko
  newName: 622054843987.dkr.ecr.eu-west-2.amazonaws.com/gigxpad-web
  newTag: a89ef6198b7f90d11ead33f36a1ba61c511b04f8-bko
